/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "ADC_DelSig.h"
#include "Vin_aliases.h"
#include "Vin.h"
#include "UART.h"
#include "ADC_Isr.h"
#include "Clock_Isr.h"
#include "Timer.h"
#include "SDA_aliases.h"
#include "SDA.h"
#include "SCL_aliases.h"
#include "SCL.h"
#include "I2C_CLK.h"
#include "I2C.h"
#include "I2C_PVT.h"
#include "SPIM.h"
#include "SPIM_PVT.h"
#include "SPIM_SCLK_aliases.h"
#include "SPIM_SCLK.h"
#include "SPIM_SS_aliases.h"
#include "SPIM_SS.h"
#include "SPIM_MISO_aliases.h"
#include "SPIM_MISO.h"
#include "SPIM_CLK.h"
#include "ADC_DelSig_AMux.h"
#include "ADC_DelSig_Ext_CP_Clk.h"
#include "ADC_DelSig_IRQ.h"
#include "ADC_DelSig_theACLK.h"
#include "UART_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

